// Code generated from bin/star-traders-sync; DO NOT EDIT.
// TestSnippetsMatchTheScript fails when they drift: a remote hub runs the
// script's own text for every write, so the two builds change it the same way.

package transfer

const (
	snapshotHubScript = "\n        set -eo pipefail\n        hub=\"$1\"; snaproot=\"$2\"; snapdir=\"$3\"; stamp=\"$4\"; keep=\"$5\"\n        snapdirs=\"$6\"; lockdir=\"$7\"\n        mkdir -p \"$snaproot\"\n        snaproot=$(cd \"$snaproot\" && pwd -P)\n        # Built under a hidden .partial- name and renamed only once its file\n        # count checks out, as snapshot_local does: a snapshot that failed\n        # part way must never look like a good one, nor take a good one'\"'\"'s\n        # place in SNAPSHOT_KEEP (#156). ls skips dot names.\n        name=\"$stamp\"\n        suffix=2\n        while [ -e \"$snaproot/$name\" ] || ! mkdir \"$snaproot/.partial-$name\" 2>/dev/null; do\n            name=\"$stamp-$suffix\"\n            suffix=$((suffix + 1))\n            [ \"$suffix\" -gt 50 ] && { echo STS_SNAP_NODIR; exit 1; }\n        done\n        partial=\"$snaproot/.partial-$name\"\n        snapdir=\"$snaproot/$name\"\n        cd \"$hub\"\n        src_n=$(find . -type f ! -path \"./$snapdirs/*\" 2>/dev/null | grep -c . || true)\n        if ! find . -type f ! -path \"./$snapdirs/*\" -print0 2>/dev/null \\\n             | cpio -0 -pdm \"$partial\" 2>/dev/null; then\n            cp -Rp \"$hub\"/ \"$partial\"/ 2>/dev/null || { echo STS_SNAP_FAIL; exit 1; }\n        fi\n        dst_n=$(find \"$partial\" -type f 2>/dev/null | grep -c . || true)\n        if [ \"${dst_n:-0}\" -lt \"${src_n:-0}\" ]; then\n            echo \"STS_SNAP_SHORT $src_n $dst_n\"\n            exit 1\n        fi\n        [ ! -e \"$snapdir\" ] && mv \"$partial\" \"$snapdir\" || { echo STS_SNAP_FAIL; exit 1; }\n        livecount=$(find \"$hub\" -maxdepth 1 -type f 2>/dev/null | grep -c . || true)\n        if [ \"$keep\" -gt 0 ] && [ \"${livecount:-0}\" -gt 0 ]; then\n            n=$(ls -1 \"$snaproot\" 2>/dev/null | grep -c . || true)\n            if [ \"${n:-0}\" -gt \"$keep\" ]; then\n                ls -1 \"$snaproot\" | LC_ALL=C sort | head -n $((n - keep)) \\\n                  | while IFS= read -r old; do\n                        [ -n \"$old\" ] || continue\n                        rm -rf \"$snaproot/$old\"\n                    done\n            fi\n        fi\n        echo \"STS_SNAP_OK $dst_n $snapdir\"\n"
	carryHubScript    = "\n        hub=\"$1\"; staged=\"$2\"; shift 2\n        [ -d \"$hub\" ] || exit 0           # no hub yet: nothing to carry\n        cd \"$hub\" || exit 3                # there but unreadable: refuse, never skip\n        n_carried=0\n        for n in \"$@\"; do\n            for f in $n; do               # a glob entry expands here, like the local side\n                [ -e \"$f\" ] || continue\n                [ -e \"$staged/$f\" ] && continue\n                if ! cp -Rp \"$f\" \"$staged\"/ 2>/dev/null; then\n                    echo \"STS_CARRY_FAIL $f\"\n                    exit 3\n                fi\n                n_carried=$((n_carried + 1))\n            done\n        done\n        echo \"STS_CARRY_OK $n_carried\"\n"
	sweepHubScript    = "\n        parent=\"$1\"\n        now=$(date -u +%s)\n        for d in \"$parent\"/.sts-incoming-*; do\n            [ -d \"$d\" ] || continue\n            m=$(stat -f%m \"$d\" 2>/dev/null || echo \"$now\")\n            [ $((now - m)) -ge 300 ] && rm -rf \"$d\"\n        done\n        exit 0\n"
	swapHubScript     = "\n            set -e\n            trap \"\" HUP INT TERM PIPE\n            hub=\"$1\"; tmp=\"$2\"; old=\"$1.sts-old-$3\"\n            rm -rf \"$old\"\n            mv \"$hub\" \"$old\"\n            if ! mv \"$tmp\" \"$hub\"; then\n                mv \"$old\" \"$hub\"\n                exit 90\n            fi\n            rm -rf \"$old\"\n"
	stageHubScript    = "rm -rf \"$1\" && mkdir -p \"$1\""
	mkdirHubScript    = "mkdir -p \"$1\""
)
