// Code generated from bin/star-traders-sync; DO NOT EDIT.
// TestSnippetsMatchTheScript fails when they drift: these are the exact
// texts the script runs on the hub, so the Go build takes and releases the
// same locks the same way while both are in use.

package lock

const (
	acquireScript = "\n        lock=\"$1\"; info=\"$lock/owner\"\n        if mkdir \"$lock\" 2>/dev/null; then\n            printf \"%s\\n%s\\n%s\\n%s\\n%s\\n%s\\n\" \"$2\" \"$3\" \"$4\" \"$(date -u +%s)\" \"$5\" \"$6\" > \"$info\"\n            echo STS_LOCK_ACQUIRED\n        elif [ ! -d \"$lock\" ]; then\n            echo STS_LOCK_NOCREATE\n        else\n            echo STS_LOCK_HELD\n            if [ -f \"$info\" ]; then\n                echo STS_OWNER\n                cat \"$info\"\n            else\n                echo STS_NO_OWNER\n                stat -f%m \"$lock\" 2>/dev/null || echo 0\n            fi\n        fi\n"
	clearScript   = "\n        lock=\"$1\"; want=\"$2\"; ttl=\"$3\"; m=\"$1.clearing\"\n        # older_than PATH SECONDS: true only for an mtime actually read. An\n        # unreadable one must never count as old: that would clear a live\n        # mutex or a young lock.\n        older_than() {\n            t=$(stat -f%m \"$1\" 2>/dev/null || stat -c%Y \"$1\" 2>/dev/null)\n            # Spelled out: this runs on the hub, where CH_DIGITS is not set.\n            case \"$t\" in \"\"|*[!0123456789]*) return 1 ;; esac\n            [ $(( $(date -u +%s) - t )) -ge \"$2\" ]\n        }\n        if ! mkdir \"$m\" 2>/dev/null; then\n            # Held for milliseconds by a live clearer. One a minute old was\n            # left by a run that died inside the clear; removing it here\n            # would be check-then-act again, so it is reported instead.\n            if older_than \"$m\" 60; then echo STS_CLEAR_DEAD; else echo STS_CLEAR_BUSY; fi\n            exit 0\n        fi\n        trap \"rmdir \\\"$m\\\" 2>/dev/null\" EXIT\n        [ -d \"$lock\" ] || { echo STS_CLEAR_GONE; exit 0; }\n        if [ \"$want\" = \"-\" ]; then\n            same=0\n            if [ ! -e \"$lock/owner\" ] && older_than \"$lock\" \"$ttl\"; then same=1; fi\n        else\n            [ \"$(sed -n 5p \"$lock/owner\" 2>/dev/null)\" = \"$want\" ] && same=1 || same=0\n        fi\n        if [ \"$same\" = 1 ]; then\n            rm -rf \"$lock\"\n            echo STS_CLEAR_OK\n        else\n            echo STS_CLEAR_CHANGED\n        fi\n"
	releaseScript = "\n        if [ \"$(sed -n 5p \"$1/owner\" 2>/dev/null)\" = \"$2\" ]; then\n            rm -rf \"$1\"\n        fi\n"
)
